name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  no_proxy: intel.com,.intel.com,localhost,127.0.0.1

jobs:
  tests:
    runs-on: [self-hosted, gklab, lgr]
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        run: |
          ./.github/workflows/build-and-test.sh
